default_stages: [pre-push]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer

- repo: https://github.com/sqlfluff/sqlfluff
  rev: 2.1.2
  hooks:
    - id: sqlfluff-lint
      name: sqlfluff-lint
      description: "Lints sql files with `SQLFluff`"
      stages: [pre-push]
      additional_dependencies: [
        'dbt-snowflake==1.5.2',
        'sqlfluff-templater-dbt==2.1.2'
      ]
      fail_fast: true

- repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  rev: v1.1.1
  hooks:
  - id: dbt-compile # Compiles dbt (necessary for future hooks)
  - id: dbt-docs-generate # Generates the dbt docs (necessary for some future hooks)
  - id: check-source-table-has-description # Ensures all source tables have descriptions
  - id: check-model-has-tests # Ensures all models have at least 2 tests
    args: ["--test-cnt", "2", "--"]
    files: ^models/
  - id: check-script-semicolon # Ensure that the model does not have a semicolon at the end of the file.
  - id: check-script-has-no-table-name # Ensures models only use source or ref macro to specify the table name.
  - id: check-model-has-all-columns # Ensures that mart models have all columns in the database also specified in the .yml
    files: ^models/marts
  - id: check-model-tags
    args: ["--tags", "hourly", "daily", "monthly", "unit_testing", "--"]
    files: ^models/
