name: 'course_advanced_dbt'
version: '1.0.0'
config-version: 2

profile: 'course_advanced_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: 'logs'
target-path: 'target'
packages-install-path: 'dbt_packages'

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  unit_testing: 'false'

on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"

seeds:
  course_advanced_dbt:
    unit_testing:
      +tags: ['unit_testing']

  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false



models:
  course_advanced_dbt:
    +materialized: view
    +grants:
      select: ['transformer', 'reporter']

  dbt_project_evaluator:
    +schema: schdwilliamsgmail_test
